# Generated by Django 3.1.7 on 2021-05-23 11:56

import datetime
import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210522_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dogum_gunu',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 23, 14, 56, 54, 586091), verbose_name='Doğum Günü'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
